### PR TITLE
Fix NPC player follow to be one step behind.

### PR DESCRIPTION
**Pull request by CodyD**
Fixed NPC follow to track player's previous step, instead of current step.

### CODE REVIEW

**Comment by ipkpjersi** [comment]
Looks good to me. I wonder how this will work with #649 if it'll improve things even further.

**Comment by CodyD** [comment]
@ipkpjersi I actually think there is a bug relating to NPCs following due to the distanceRequired method. I was testing out some of the NPCs defined within, and none of them are able to follow. I'll take a look tonight and push a fix for that, it might help with what you're working on.

**Comment by ipkpjersi** [comment]
It's possible I already have a fix for it, I did change distanceRequired in one or two of my PRs.

**Comment by CodyD** [comment]
@ipkpjersi Tested locally with some code snippets, it wasn't really an issue in the game logic per se, it was more closely related to summoning aggressive NPCs that had ranged attacks.

**Comment by ipkpjersi** [comment]
I think one of my PRs possibly also addresses that issue, can't recall which one since I opened up a few.

**Comment by CodyD** [comment]
Caused issues in combat.

**Pull request closed without merging**
