### PR TITLE
Merge The File&Game Servers Into One Module

### PR DESCRIPTION
**Pull request by Dark98**

### CODE REVIEW

**Comment by Dark98** [comment]
@dginovker @RedSparr0w thoughts on doing this?

**Comment by dginovker** [comment]
Honestly ya big support. 2006scape being easy to setup is a big advantage of the project

**Review by dginovker — APPROVED** [review]

**Comment by RedSparr0w** [comment]
Do you think with all these possible config options it may be worth adding a server start variable for setting the config file?
Something like:
```console
java -jar server.jar --config ./world2.cfg
```
which would load a config file as the defaults instead of whatever the server was built with in `GameConstants.java`?

**Comment by Dark98** [comment]
> Do you think with all these possible config options it may be worth adding a server start variable for setting the config file? Something like:
> 
> ```
> java -jar server.jar --config ./world2.cfg
> ```
> 
> which would load a config file as the defaults instead of whatever the server was built with in `GameConstants.java`?

If we do that then we can basically just convert the existing JSON loader that's used for the discord Bot token and a few other things into a JSON loader for the GameConstants vars?

**Comment by RedSparr0w** [comment]
> > Do you think with all these possible config options it may be worth adding a server start variable for setting the config file? Something like:
> > ```
> > java -jar server.jar --config ./world2.cfg
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which would load a config file as the defaults instead of whatever the server was built with in `GameConstants.java`?
> 
> If we do that then we can basically just convert the existing JSON loader that's used for the discord Bot token and a few other things into a JSON loader for the GameConstants vars?

Yeah, that's probably the easiest way to handle it, just have some default options for if the config doesn't have something set too.

**Comment by Dark98** [comment]
> Do you think with all these possible config options it may be worth adding a server start variable for setting the config file? Something like:
> 
> ```
> java -jar server.jar --config ./world2.cfg
> ```
> 
> which would load a config file as the defaults instead of whatever the server was built with in `GameConstants.java`?

Should we have the default config as the one set in GameConstants.java, then any vars that are set in the used config get updated?
 Or have a default config.json that it falls back to for setting the vars In GameConstants.java if the -c/-config argument isn't used?

**Comment by RedSparr0w** [comment]
> Should we have the default config as what's set in GameConstants.java, then any vars that are set in the used config get changed/used instead?

That one IMO.

Have default options set,
Any options that are specified in the config will overwrite the defaults,
If they aren't in the config, then they just stay as the default.

**Comment by Dark98** [comment]
Okay, sweet :) this only need the rest of the vars adding to the ConfigLoader then it's ready for merge then

**Pull request merged**
