### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by MatthewBishop**
This is a PR for bug fixes/current issues.

Initial commit should fix https://github.com/2006-Scape/2006Scape/issues/594

### CODE REVIEW

**Comment by MatthewBishop** [comment]
fixes https://github.com/2006-Scape/2006Scape/issues/599

**Comment by MatthewBishop** [comment]
Fixes https://github.com/2006-Scape/2006Scape/issues/600

**Comment by MatthewBishop** [comment]
Fixes https://github.com/2006-Scape/2006Scape/issues/597

**Comment by halogod35** [comment]
Also fixes #598

**Comment by MatthewBishop** [comment]
Also fixes https://github.com/2006-Scape/2006Scape/issues/605

**Comment by MatthewBishop** [comment]
Also fixes https://github.com/2006-Scape/2006Scape/issues/604

**Pull request merged**
